import { useState } from 'react';
import { ArrowDown, ArrowUpRight, BookOpen, Check, ChevronRight, Clock3, Copy, Leaf, Menu, Sparkles, X } from 'lucide-react';
import './_group.css';

const exhibits = [
  { id: 'origin', no: '01', title: 'A beginning with a boundary', label: 'ORIGIN ROOM', text: 'Before the procession, there is a threshold. Ganesha is invited into the home as a guardian of beginnings, wisdom and the courage to meet what blocks us.', mark: 'I', color: '#d9612e' },
  { id: 'public', no: '02', title: 'When a home became a city', label: 'PUBLIC MEMORY', text: 'In Maharashtra, a private ritual grew into a public gathering. The Sarvajanik festival gave neighbours a shared room for music, ideas and civic belonging.', mark: 'II', color: '#53657e' },
  { id: 'earth', no: '03', title: 'Clay returns to the river', label: 'LIVING MATERIAL', text: 'The final gesture is not an ending. Natural clay dissolves, returning the form to water and asking us to celebrate without leaving a wound behind.', mark: 'III', color: '#829078' },
];

function Motif({ className = '' }: { className?: string }) {
  return <svg className={className} viewBox="0 0 180 180" aria-hidden="true"><circle cx="90" cy="90" r="66" fill="none" stroke="currentColor" strokeWidth="1" /><circle cx="90" cy="90" r="44" fill="none" stroke="currentColor" strokeWidth="1" strokeDasharray="2 7" /><path d="M90 24v132M24 90h132M43 43l94 94M137 43l-94 94" fill="none" stroke="currentColor" strokeWidth=".6" /><circle cx="90" cy="90" r="5" fill="currentColor" /></svg>;
}

function SectionLabel({ children }: { children: string }) {
  return <p className="museum-mono text-[10px] uppercase tracking-[.22em] text-[#9a5a36]">{children}</p>;
}

export function FestivalMuseum() {
  const [active, setActive] = useState('origin');
  const [menuOpen, setMenuOpen] = useState(false);
  const [revealed, setRevealed] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const [quizAnswer, setQuizAnswer] = useState<string | null>(null);
  const goTo = (id: string) => { setActive(id); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); setMenuOpen(false); };
  const copyWish = async () => { await navigator.clipboard?.writeText('May every new beginning carry a little more wisdom. Ganpati Bappa Morya.'); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };

  return (
    <div className="museum-shell museum-grain">
      <header className="fixed left-0 right-0 top-0 z-20 border-b border-white/10 bg-[#091332]/90 text-[#f7efd9] backdrop-blur-md">
        <div className="mx-auto flex h-[68px] max-w-[1380px] items-center justify-between px-5 md:px-10">
          <button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="flex items-center gap-3 text-left" aria-label="Return to museum entrance">
            <span className="flex h-8 w-8 items-center justify-center border border-[#f3b43f] text-[#f3b43f]"><span className="museum-serif text-lg">R</span></span>
            <span><span className="block text-[10px] font-semibold tracking-[.18em]">RAINBOW INTERNATIONAL</span><span className="museum-mono block text-[9px] tracking-[.16em] text-[#c9bda6]">SCHOOL · THANE</span></span>
          </button>
          <div className="hidden items-center gap-8 md:flex"><span className="museum-mono text-[10px] text-[#c9bda6]">EXHIBITION  /  2026</span><button onClick={() => goTo('learn')} className="flex items-center gap-2 text-xs uppercase tracking-[.13em] text-[#f3b43f]">Learning desk <ArrowUpRight size={14} /></button></div>
          <button onClick={() => setMenuOpen(!menuOpen)} className="md:hidden" aria-expanded={menuOpen} aria-label="Open museum navigation">{menuOpen ? <X size={21} /> : <Menu size={21} />}</button>
        </div>
        {menuOpen && <div className="border-t border-white/10 bg-[#091332] px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm">{exhibits.map((e) => <button className="text-left text-[#f7efd9]" key={e.id} onClick={() => goTo(e.id)}>{e.no} — {e.title}</button>)}<button className="text-left text-[#f3b43f]" onClick={() => goTo('learn')}>Learning desk</button></div></div>}
      </header>

      <main>
        <section className="relative flex min-h-[760px] items-end overflow-hidden bg-[#091332] px-5 pb-20 pt-32 text-[#f7efd9] md:min-h-[850px] md:px-12 md:pb-28">
          <div className="absolute -right-28 top-28 h-[560px] w-[560px] text-[#f3b43f]/30 md:right-[7%]"><Motif className="h-full w-full animate-[spin_80s_linear_infinite]" /></div>
          <div className="absolute left-[38%] top-40 h-px w-[45%] bg-[#f3b43f]/40" />
          <div className="relative z-10 mx-auto w-full max-w-[1380px]">
            <div className="mb-12 flex items-center gap-3"><span className="h-px w-14 bg-[#d9612e]" /><span className="museum-mono text-[10px] uppercase tracking-[.22em] text-[#ddcda8]">A digital exhibition for curious minds</span></div>
            <div className="max-w-[950px]"><h1 className="museum-serif text-[clamp(3.7rem,10vw,9.5rem)] leading-[.88] tracking-[-.07em]">The festival<br /><em className="font-normal text-[#f3b43f]">of beginnings.</em></h1><p className="mt-9 max-w-[520px] text-base leading-7 text-[#d9d1c2] md:text-lg">Ganesh Chaturthi is not one story. It is a collection of rooms — memory, material, movement and meaning — opened for ten days.</p></div>
            <div className="mt-16 flex flex-wrap items-end justify-between gap-8 border-t border-white/15 pt-5"><div><p className="museum-mono text-[10px] uppercase tracking-[.2em] text-[#9da8bd]">The 2026 edition</p><p className="mt-2 text-sm text-[#f7efd9]">14 September — 25 September</p></div><button onClick={() => goTo('origin')} className="group flex items-center gap-3 text-xs uppercase tracking-[.15em] text-[#f3b43f]">Enter the exhibition <span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#f3b43f]/60 transition-transform group-hover:translate-y-1"><ArrowDown size={15} /></span></button></div>
          </div>
        </section>

        <div className="sticky top-[68px] z-10 border-b border-[#d8cdb5] bg-[#f5edd9]/95 backdrop-blur"><div className="mx-auto flex max-w-[1380px] items-center gap-5 overflow-x-auto px-5 py-3 md:px-12"><span className="museum-mono shrink-0 text-[9px] uppercase tracking-[.18em] text-[#9a5a36]">Your route</span>{exhibits.map((e) => <button onClick={() => goTo(e.id)} key={e.id} className={`flex shrink-0 items-center gap-2 text-xs transition-colors ${active === e.id ? 'font-bold text-[#d9612e]' : 'text-[#526078]'}`}><span className="museum-mono text-[10px]">{e.no}</span>{e.label}</button>)}<button onClick={() => goTo('learn')} className="flex shrink-0 items-center gap-2 text-xs text-[#526078]"><span className="museum-mono text-[10px]">04</span>LEARNING DESK</button></div></div>

        <section className="mx-auto grid max-w-[1380px] gap-10 px-5 py-20 md:grid-cols-[.7fr_1.3fr] md:px-12 md:py-32" id="origin">
          <div className="md:sticky md:top-40 md:self-start"><SectionLabel>Room one / Origin</SectionLabel><h2 className="museum-serif mt-4 max-w-[420px] text-4xl leading-[1.05] tracking-[-.04em] text-[#132044] md:text-6xl">Look closely.<br /><span className="text-[#d9612e]">The symbols are speaking.</span></h2><p className="mt-6 max-w-[310px] text-sm leading-6 text-[#526078]">A guided look at the familiar form — not as decoration, but as a compact lesson in how to live.</p></div>
          <div className="grid gap-5 md:grid-cols-2">
            {[['01','The large ears','Listen before you answer. Wisdom begins with making room for another voice.'],['02','The single tusk','Keep what is useful. Let go of what keeps you from moving forward.'],['03','The small mouse','No challenge is too large when curiosity is allowed to lead.'],['04','The modak','The sweetest rewards are made slowly, by effort and attention.']].map(([num, title, text], index) => <button key={num} onClick={() => setRevealed(revealed === index ? null : index)} className={`group min-h-[210px] border p-6 text-left transition-all ${revealed === index ? 'border-[#d9612e] bg-[#d9612e] text-[#fff8e9]' : 'border-[#d8cdb5] bg-[#f9f3e5] text-[#132044] hover:-translate-y-1 hover:border-[#d9612e]'}`}><span className="museum-mono text-[10px] opacity-60">{num}</span><h3 className="museum-serif mt-10 text-2xl leading-tight">{title}</h3><p className="mt-3 text-sm leading-6 opacity-80">{text}</p><span className="mt-4 block text-[10px] uppercase tracking-[.16em] opacity-60">{revealed === index ? 'Close note' : 'Open curator note'}</span></button>)}
          </div>
        </section>

        <section className="bg-[#101e4b] px-5 py-20 text-[#f7efd9] md:px-12 md:py-28" id="public">
          <div className="mx-auto max-w-[1380px]"><div className="flex flex-col justify-between gap-10 md:flex-row"><div><SectionLabel>Room two / Public memory</SectionLabel><h2 className="museum-serif mt-4 max-w-[670px] text-4xl leading-[1.04] tracking-[-.04em] md:text-7xl">From a private ritual<br /><em className="font-normal text-[#f3b43f]">to a public room.</em></h2></div><div className="max-w-[270px] border-l border-[#f3b43f]/50 pl-5 text-sm leading-6 text-[#cdd0d1]">In the 1890s, public Ganeshotsav became a way to gather, learn and build community during a changing India.</div></div><div className="mt-16 grid items-end gap-8 md:grid-cols-[1fr_1.7fr]"><div className="relative h-[270px] overflow-hidden border border-[#f3b43f]/40 bg-[#d9612e] p-7 text-[#101e4b]"><span className="museum-mono text-[10px]">ARCHIVE / 1893</span><div className="absolute -bottom-20 -right-12 h-64 w-64 opacity-40"><Motif className="h-full w-full" /></div><p className="museum-serif absolute bottom-7 left-7 max-w-[200px] text-3xl leading-none">Many voices.<br />One square.</p></div><div className="grid gap-5 border-t border-white/20 pt-5 md:grid-cols-3">{[['1892','The first public celebrations take shape in Pune.'],['1893','Lokmanya Tilak helps turn the festival into a shared civic platform.'],['2026','The invitation remains: gather with care, learn together.']].map(([year, copy]) => <div key={year}><span className="museum-mono text-sm text-[#f3b43f]">{year}</span><p className="mt-3 text-sm leading-6 text-[#d3d3ca]">{copy}</p></div>)}</div></div></div>
        </section>

        <section className="bg-[#dce3d4] px-5 py-20 md:px-12 md:py-28" id="earth"><div className="mx-auto max-w-[1380px]"><div className="flex flex-col justify-between gap-8 md:flex-row"><div><SectionLabel>Room three / Living material</SectionLabel><h2 className="museum-serif mt-4 max-w-[720px] text-4xl leading-[1.04] tracking-[-.04em] text-[#132044] md:text-7xl">A beautiful form<br />can <em className="font-normal text-[#536b55]">return.</em></h2></div><Leaf className="h-12 w-12 text-[#536b55]" strokeWidth={1} /></div><div className="mt-16 grid gap-12 md:grid-cols-[1.1fr_.9fr]"><div className="max-w-[580px]"><p className="museum-serif text-2xl leading-9 text-[#132044]">“The best celebration leaves the water clearer than it found it.”</p><p className="mt-6 text-base leading-7 text-[#526078]">Choose natural shadu clay, use a small home idol, and immerse in a designated tank. The ritual keeps its meaning when the material is treated with respect.</p><div className="mt-10 flex gap-8 border-t border-[#829078]/60 pt-5"><div><span className="museum-mono text-2xl text-[#536b55]">01</span><p className="mt-2 text-xs text-[#526078]">Natural clay</p></div><div><span className="museum-mono text-2xl text-[#536b55]">10</span><p className="mt-2 text-xs text-[#526078]">Days of welcome</p></div><div><span className="museum-mono text-2xl text-[#536b55]">01</span><p className="mt-2 text-xs text-[#526078]">Shared promise</p></div></div></div><div className="relative flex min-h-[270px] items-center justify-center border border-[#829078] bg-[#c5d0bd]"><Motif className="absolute h-64 w-64 text-[#536b55]/40" /><div className="relative text-center"><p className="museum-mono text-[10px] uppercase tracking-[.2em] text-[#536b55]">Material study</p><p className="museum-serif mt-3 text-4xl text-[#536b55]">clay → water</p></div></div></div></div></section>

        <section className="bg-[#f5edd9] px-5 py-20 md:px-12 md:py-28" id="learn"><div className="mx-auto max-w-[1380px]"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><SectionLabel>Learning desk / For students</SectionLabel><h2 className="museum-serif mt-4 max-w-[760px] text-4xl leading-[1.04] tracking-[-.04em] text-[#132044] md:text-7xl">Take a question<br />with you.</h2></div><div className="flex items-center gap-2 text-xs text-[#526078]"><BookOpen size={16} /> Quick exhibit notes</div></div><div className="mt-14 grid gap-5 md:grid-cols-[1.25fr_.75fr]"><div className="border border-[#d8cdb5] bg-[#f9f3e5] p-6 md:p-9"><div className="flex items-center justify-between"><span className="museum-mono text-[10px] uppercase tracking-[.18em] text-[#9a5a36]">Curator quiz / 01</span><Clock3 size={17} className="text-[#9a5a36]" /></div><h3 className="museum-serif mt-14 text-3xl text-[#132044]">Why is Ganesha worshipped before other gods?</h3><div className="mt-8 grid gap-3">{['Because he is the god of wealth','Because wisdom helps us begin well','Because his festival lasts ten days'].map((answer) => <button key={answer} onClick={() => setQuizAnswer(answer)} className={`flex items-center justify-between border px-4 py-3 text-left text-sm transition-colors ${quizAnswer === answer ? 'border-[#536b55] bg-[#dce3d4] text-[#132044]' : 'border-[#d8cdb5] hover:border-[#d9612e]'}`}>{answer}{quizAnswer === answer && <Check size={16} />}</button>)}</div>{quizAnswer && <p className="mt-5 border-l-2 border-[#536b55] pl-4 text-sm leading-6 text-[#536b55]">Correct. The story reminds us that thoughtful beginnings can change the whole journey.</p>}</div><div className="bg-[#d9612e] p-6 text-[#fff8e9] md:p-9"><Sparkles size={20} /><h3 className="museum-serif mt-10 text-3xl leading-tight">A ready-to-read opening</h3><p className="mt-5 text-sm leading-6 text-[#fff1df]">“Good morning. Today I would like to share why Ganesh Chaturthi is more than a celebration — it is a lesson in wisdom, community and responsible choices.”</p><button onClick={copyWish} className="mt-8 flex items-center gap-2 border border-[#fff1df]/60 px-4 py-3 text-xs uppercase tracking-[.14em] hover:bg-[#b94d26]">{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? 'Copied' : 'Copy opening'}</button></div></div></div></section>

        <section className="relative overflow-hidden bg-[#091332] px-5 py-24 text-[#f7efd9] md:px-12 md:py-36"><div className="absolute right-[-100px] top-[-150px] h-[500px] w-[500px] text-[#f3b43f]/20"><Motif className="h-full w-full" /></div><div className="relative mx-auto max-w-[1380px]"><SectionLabel>Final room / The invitation</SectionLabel><h2 className="museum-serif mt-5 max-w-[880px] text-5xl leading-[.98] tracking-[-.05em] md:text-8xl">Bring the lesson<br /><em className="font-normal text-[#f3b43f]">home.</em></h2><div className="mt-12 flex flex-col justify-between gap-8 border-t border-white/15 pt-6 md:flex-row md:items-end"><p className="max-w-[450px] text-base leading-7 text-[#d8d1c4]">On 14 September, make space for a beginning. On 25 September, let the form return. In between, ask better questions.</p><button onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} className="group flex items-center gap-3 text-xs uppercase tracking-[.16em] text-[#f3b43f]">Re-enter the museum <span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#f3b43f]/60 transition-transform group-hover:-translate-y-1"><ChevronRight size={15} /></span></button></div><div className="mt-20 flex flex-wrap justify-between gap-4 border-t border-white/10 pt-5 text-[10px] uppercase tracking-[.16em] text-[#8490a8]"><span>Rainbow International School · Thane</span><span>For families, students and teachers</span><span>Ganesh Chaturthi 2026</span></div></div></section>
      </main>
    </div>
  );
}