uploads = []
outputs = []

[[generated]]
id = "kJ6UP37T2969NQ_IdOsdd"
uri = "file://client/public/amenities/amphitheatre.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wNL8ByHvcKZxj5P6XOQAw"
uri = "file://client/public/amenities/music-room.png"
type = "image"
title = "generated_image"

[[generated]]
id = "weE57aQErmhHdQHBHJn-7"
uri = "file://client/public/amenities/art-craft-room.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ghdCGt0Zt0yq3Rjm8VhSn"
uri = "file://client/public/amenities/multipurpose-hall.png"
type = "image"
title = "generated_image"

[[generated]]
id = "9wnATl6YYVct6IwbnZ3NA"
uri = "file://client/public/amenities/cricket-ground.png"
type = "image"
title = "generated_image"

[[generated]]
id = "qKi8dsFyYyjckoDo0XnLL"
uri = "file://client/public/amenities/football-turf.png"
type = "image"
title = "generated_image"

[[generated]]
id = "2sitqZiu_l2L54wW5GExb"
uri = "file://client/public/amenities/skating-rink.png"
type = "image"
title = "generated_image"

[[generated]]
id = "M1MreJEo___lzPGfxZkIT"
uri = "file://client/public/amenities/swimming-pool.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LGHvbfUo9-PCe0hJ9dzfa"
uri = "file://client/public/amenities/rock-climbing.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ri_Bf4ldXc4ISeac1CoZ7"
uri = "file://client/public/amenities/basketball.png"
type = "image"
title = "generated_image"

[[generated]]
id = "WceIEPiXzOnl6e7as1CyD"
uri = "file://client/public/amenities/table-tennis.png"
type = "image"
title = "generated_image"

[[generated]]
id = "4_JG1MivOVf4cMVQ2EoM0"
uri = "file://client/public/amenities/chess.png"
type = "image"
title = "generated_image"

[[generated]]
id = "pjA039JEb-hbHKN62VnfP"
uri = "file://client/public/amenities/carrom.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZkwuLzlagwbhn3xMzgKBw"
uri = "file://client/public/amenities/karate.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zxNukYRZbBFRB5Bt0UQNC"
uri = "file://client/public/amenities/elearning-classroom.png"
type = "image"
title = "generated_image"

[[generated]]
id = "kE3jTcyC4h-gvi8RSN37_"
uri = "file://client/public/amenities/storage-bags-books.png"
type = "image"
title = "generated_image"

[[generated]]
id = "6pP2eA2VsNg5q8bClZJtU"
uri = "file://client/public/amenities/reading-room.png"
type = "image"
title = "generated_image"

[[generated]]
id = "a3AkWgo90jcHQkjZCqGgw"
uri = "file://client/public/amenities/maths-science-lab.png"
type = "image"
title = "generated_image"

[[generated]]
id = "LaNW3XsvGlaDvUuWqh49V"
uri = "file://client/public/amenities/school-library.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3lGiV23E6D-iqBDKAYvyy"
uri = "file://client/public/amenities/school-bank.png"
type = "image"
title = "generated_image"

[[generated]]
id = "i7pzV8Lo81M4dIuRMJqGX"
uri = "file://client/public/amenities/ac-classrooms.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hhZl5XT7lpZ3FBQtWm8H0"
uri = "file://client/public/amenities/generator-backup.png"
type = "image"
title = "generated_image"

[[generated]]
id = "0D5TLSriU4r8ObJGLlfKZ"
uri = "file://client/public/amenities/hygiene.png"
type = "image"
title = "generated_image"

[[generated]]
id = "r4jl6Q9RE9uYnVq1vpl2H"
uri = "file://client/public/amenities/fire-compliance.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tdd_X21WaBmko4PQzv8MI"
uri = "file://client/public/amenities/infirmary.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YYLWQTgbha_zU6nad4oK4"
uri = "file://client/public/amenities/ambulance.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DhIBcacN4MA4oSCYne2fu"
uri = "file://client/public/amenities/cctv-surveillance.png"
type = "image"
title = "generated_image"

[[generated]]
id = "sm0E_qV9nYQE0jP3XZdGH"
uri = "file://client/public/amenities/metal-detectors.png"
type = "image"
title = "generated_image"

[[generated]]
id = "p9qV96aJSEhQ0xAIuefke"
uri = "file://client/public/amenities/organic-farming-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "na1Oje8o9S-vnOdRLGAay"
uri = "file://client/public/amenities/organic-farming-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7L_ZG3CdkA4mPc3uXGY2q"
uri = "file://client/public/amenities/organic-farming-3.png"
type = "image"
title = "generated_image"
