// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/marketing-dashboard/QuietBlue.tsx": () => import("../components/mockups/marketing-dashboard/QuietBlue.tsx"),
  "./components/mockups/marketing-dashboard/SoftSage.tsx": () => import("../components/mockups/marketing-dashboard/SoftSage.tsx"),
  "./components/mockups/marketing-dashboard/WarmSand.tsx": () => import("../components/mockups/marketing-dashboard/WarmSand.tsx")
};
